
Lmod is automatically replacing "scicomp-python-env/2025.1" with "mamba/2025.1".

Assuming unrestricted shared filesystem usage.
Building DAG of jobs...
Your conda installation is not configured to use strict channel priorities. This is however crucial for having robust and correct environments (for details, see https://conda-forge.org/docs/user/tipsandtricks.html). Please consider to configure strict priorities by executing 'conda config --set channel_priority strict'.
Using shell: /usr/bin/bash
Provided cores: 16
Rules claiming more threads will be scaled down.
Job stats:
job        count
-------  -------
all            1
cluster       24
total         25

Select jobs to execute...
Execute 16 jobs...

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/6/gmm_cluster.csv, out/clusters/dtu/6/gmm_cluster_centroids.csv, out/clusters/dtu/6/gmm_cluster_covariances.csv
    jobid: 16
    reason: Missing output files: out/clusters/dtu/6/gmm_cluster.csv, out/clusters/dtu/6/gmm_cluster_centroids.csv
    wildcards: study=dtu, cluster_num=6, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/9/gmm_cluster.csv, out/clusters/dtu/9/gmm_cluster_centroids.csv, out/clusters/dtu/9/gmm_cluster_covariances.csv
    jobid: 32
    reason: Missing output files: out/clusters/dtu/9/gmm_cluster_centroids.csv, out/clusters/dtu/9/gmm_cluster.csv
    wildcards: study=dtu, cluster_num=9, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/11/gmm_cluster.csv, out/clusters/tesserae/11/gmm_cluster_centroids.csv, out/clusters/tesserae/11/gmm_cluster_covariances.csv
    jobid: 37
    reason: Missing output files: out/clusters/tesserae/11/gmm_cluster_centroids.csv, out/clusters/tesserae/11/gmm_cluster.csv
    wildcards: study=tesserae, cluster_num=11, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/8/gmm_cluster.csv, out/clusters/momo/8/gmm_cluster_centroids.csv, out/clusters/momo/8/gmm_cluster_covariances.csv
    jobid: 26
    reason: Missing output files: out/clusters/momo/8/gmm_cluster_centroids.csv, out/clusters/momo/8/gmm_cluster.csv
    wildcards: study=momo, cluster_num=8, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/10/gmm_cluster.csv, out/clusters/dtu/10/gmm_cluster_centroids.csv, out/clusters/dtu/10/gmm_cluster_covariances.csv
    jobid: 36
    reason: Missing output files: out/clusters/dtu/10/gmm_cluster_centroids.csv, out/clusters/dtu/10/gmm_cluster.csv
    wildcards: study=dtu, cluster_num=10, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/6/gmm_cluster.csv, out/clusters/momo/6/gmm_cluster_centroids.csv, out/clusters/momo/6/gmm_cluster_covariances.csv
    jobid: 8
    reason: Missing output files: out/clusters/momo/6/gmm_cluster.csv, out/clusters/momo/6/gmm_cluster_centroids.csv
    wildcards: study=momo, cluster_num=6, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/11/gmm_cluster.csv, out/clusters/dtu/11/gmm_cluster_centroids.csv, out/clusters/dtu/11/gmm_cluster_covariances.csv
    jobid: 40
    reason: Missing output files: out/clusters/dtu/11/gmm_cluster_centroids.csv, out/clusters/dtu/11/gmm_cluster.csv
    wildcards: study=dtu, cluster_num=11, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:31 2025]
localrule cluster:
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/7/gmm_cluster.csv, out/clusters/dtu/7/gmm_cluster_centroids.csv, out/clusters/dtu/7/gmm_cluster_covariances.csv
    jobid: 24
    reason: Missing output files: out/clusters/dtu/7/gmm_cluster.csv, out/clusters/dtu/7/gmm_cluster_centroids.csv
    wildcards: study=dtu, cluster_num=7, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/8/gmm_cluster.csv, out/clusters/tesserae/8/gmm_cluster_centroids.csv, out/clusters/tesserae/8/gmm_cluster_covariances.csv
    jobid: 25
    reason: Missing output files: out/clusters/tesserae/8/gmm_cluster_centroids.csv, out/clusters/tesserae/8/gmm_cluster.csv
    wildcards: study=tesserae, cluster_num=8, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/6/gmm_cluster.csv, out/clusters/tesserae/6/gmm_cluster_centroids.csv, out/clusters/tesserae/6/gmm_cluster_covariances.csv
    jobid: 1
    reason: Missing output files: out/clusters/tesserae/6/gmm_cluster.csv, out/clusters/tesserae/6/gmm_cluster_centroids.csv
    wildcards: study=tesserae, cluster_num=6, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/7/gmm_cluster.csv, out/clusters/momo/7/gmm_cluster_centroids.csv, out/clusters/momo/7/gmm_cluster_covariances.csv
    jobid: 22
    reason: Missing output files: out/clusters/momo/7/gmm_cluster.csv, out/clusters/momo/7/gmm_cluster_centroids.csv
    wildcards: study=momo, cluster_num=7, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/9/gmm_cluster.csv, out/clusters/tesserae/9/gmm_cluster_centroids.csv, out/clusters/tesserae/9/gmm_cluster_covariances.csv
    jobid: 29
    reason: Missing output files: out/clusters/tesserae/9/gmm_cluster.csv, out/clusters/tesserae/9/gmm_cluster_centroids.csv
    wildcards: study=tesserae, cluster_num=9, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/7/gmm_cluster.csv, out/clusters/tesserae/7/gmm_cluster_centroids.csv, out/clusters/tesserae/7/gmm_cluster_covariances.csv
    jobid: 21
    reason: Missing output files: out/clusters/tesserae/7/gmm_cluster.csv, out/clusters/tesserae/7/gmm_cluster_centroids.csv
    wildcards: study=tesserae, cluster_num=7, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/8/gmm_cluster.csv, out/clusters/dtu/8/gmm_cluster_centroids.csv, out/clusters/dtu/8/gmm_cluster_covariances.csv
    jobid: 28
    reason: Missing output files: out/clusters/dtu/8/gmm_cluster.csv, out/clusters/dtu/8/gmm_cluster_centroids.csv
    wildcards: study=dtu, cluster_num=8, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/10/gmm_cluster.csv, out/clusters/tesserae/10/gmm_cluster_centroids.csv, out/clusters/tesserae/10/gmm_cluster_covariances.csv
    jobid: 33
    reason: Missing output files: out/clusters/tesserae/10/gmm_cluster.csv, out/clusters/tesserae/10/gmm_cluster_centroids.csv
    wildcards: study=tesserae, cluster_num=10, algo=gmm
    resources: tmpdir=/tmp

[Wed Aug 27 16:16:32 2025]
localrule cluster:
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/11/gmm_cluster.csv, out/clusters/momo/11/gmm_cluster_centroids.csv, out/clusters/momo/11/gmm_cluster_covariances.csv
    jobid: 38
    reason: Missing output files: out/clusters/momo/11/gmm_cluster_centroids.csv, out/clusters/momo/11/gmm_cluster.csv
    wildcards: study=momo, cluster_num=11, algo=gmm
    resources: tmpdir=/tmp

Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Activating conda environment: .snakemake/conda/ab5233add898528c77eec06aa91604d6_
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpojcyyb1c.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpojcyyb1c.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp26xlmtsp.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp26xlmtsp.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpixf2z1wj.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpixf2z1wj.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp87fpwdu7.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp87fpwdu7.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '6' instead.
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '7' instead.
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '8' instead.
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '11' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp26xlmtsp.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:10 2025]
Error in rule cluster:
    jobid: 26
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/8/gmm_cluster.csv, out/clusters/momo/8/gmm_cluster_centroids.csv, out/clusters/momo/8/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpixf2z1wj.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:10 2025]
Error in rule cluster:
    jobid: 22
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/7/gmm_cluster.csv, out/clusters/momo/7/gmm_cluster_centroids.csv, out/clusters/momo/7/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpojcyyb1c.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:10 2025]
Error in rule cluster:
    jobid: 8
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/6/gmm_cluster.csv, out/clusters/momo/6/gmm_cluster_centroids.csv, out/clusters/momo/6/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp87fpwdu7.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:10 2025]
Error in rule cluster:
    jobid: 38
    input: data/processed/momo/all_features_clean.csv
    output: out/clusters/momo/11/gmm_cluster.csv, out/clusters/momo/11/gmm_cluster_centroids.csv, out/clusters/momo/11/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpmp7mtjo6.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpmp7mtjo6.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '9' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpmp7mtjo6.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:16 2025]
Error in rule cluster:
    jobid: 32
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/9/gmm_cluster.csv, out/clusters/dtu/9/gmm_cluster_centroids.csv, out/clusters/dtu/9/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpt6i7xy8p.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpt6i7xy8p.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '10' instead.
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpyo8h3m6l.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpyo8h3m6l.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '9' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpt6i7xy8p.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:17 2025]
Error in rule cluster:
    jobid: 33
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/10/gmm_cluster.csv, out/clusters/tesserae/10/gmm_cluster_centroids.csv, out/clusters/tesserae/10/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpyo8h3m6l.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:17 2025]
Error in rule cluster:
    jobid: 29
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/9/gmm_cluster.csv, out/clusters/tesserae/9/gmm_cluster_centroids.csv, out/clusters/tesserae/9/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp9nlh_5fo.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp9nlh_5fo.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '6' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp9nlh_5fo.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:19 2025]
Error in rule cluster:
    jobid: 1
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/6/gmm_cluster.csv, out/clusters/tesserae/6/gmm_cluster_centroids.csv, out/clusters/tesserae/6/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp_h3vnzv9.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp_h3vnzv9.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '11' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmp_h3vnzv9.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:22 2025]
Error in rule cluster:
    jobid: 37
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/11/gmm_cluster.csv, out/clusters/tesserae/11/gmm_cluster_centroids.csv, out/clusters/tesserae/11/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpd9xuxp8i.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpd9xuxp8i.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '11' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpd9xuxp8i.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:23 2025]
Error in rule cluster:
    jobid: 40
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/11/gmm_cluster.csv, out/clusters/dtu/11/gmm_cluster_centroids.csv, out/clusters/dtu/11/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpjvpa1dlz.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpjvpa1dlz.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '8' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpjvpa1dlz.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:24 2025]
Error in rule cluster:
    jobid: 25
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/8/gmm_cluster.csv, out/clusters/tesserae/8/gmm_cluster_centroids.csv, out/clusters/tesserae/8/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpa307gyue.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpa307gyue.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '8' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpa307gyue.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:25 2025]
Error in rule cluster:
    jobid: 28
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/8/gmm_cluster.csv, out/clusters/dtu/8/gmm_cluster_centroids.csv, out/clusters/dtu/8/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpqweao72o.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpqweao72o.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '10' instead.
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpneb0m2yt.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpneb0m2yt.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpauwvzoi3.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpauwvzoi3.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '6' instead.
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '7' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpqweao72o.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:26 2025]
Error in rule cluster:
    jobid: 36
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/10/gmm_cluster.csv, out/clusters/dtu/10/gmm_cluster_centroids.csv, out/clusters/dtu/10/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpneb0m2yt.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:26 2025]
Error in rule cluster:
    jobid: 16
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/6/gmm_cluster.csv, out/clusters/dtu/6/gmm_cluster_centroids.csv, out/clusters/dtu/6/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpauwvzoi3.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:26 2025]
Error in rule cluster:
    jobid: 24
    input: data/processed/dtu/all_features_clean.csv
    output: out/clusters/dtu/7/gmm_cluster.csv, out/clusters/dtu/7/gmm_cluster_centroids.csv, out/clusters/dtu/7/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Traceback (most recent call last):
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpn5l2bdsf.run.py", line 46, in <module>
    main(snakemake.input, snakemake.output, snakemake.params)
  File "/scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpn5l2bdsf.run.py", line 35, in main
    labels, centroids, covariances, model_selection_scores = model.run_pipeline()
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 354, in run_pipeline
    labels = self.fit_predict(self.model, X)
  File "/scratch/work/luongn1/digirhythm-v2/workflow/rules/../scripts/clusters/base.py", line 198, in fit_predict
    labels = model.fit_predict(X)
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 1344, in wrapper
    estimator._validate_params()
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "/home/luongn1/.local/lib/python3.9/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n_components' parameter of GaussianMixture must be an int in the range [1, inf). Got '7' instead.
RuleException:
CalledProcessError in file /scratch/work/luongn1/digirhythm-v2/workflow/rules/cluster.smk, line 46:
Command 'source /appl/scibuilder-mamba/aalto-rhel9/prod/software/mamba/2025.1/f67be15/bin/activate '/scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_'; set -euo pipefail;  python /scratch/work/luongn1/digirhythm-v2/.snakemake/scripts/tmpn5l2bdsf.run.py' returned non-zero exit status 1.
[Wed Aug 27 16:17:27 2025]
Error in rule cluster:
    jobid: 21
    input: data/processed/tesserae/all_features_clean.csv
    output: out/clusters/tesserae/7/gmm_cluster.csv, out/clusters/tesserae/7/gmm_cluster_centroids.csv, out/clusters/tesserae/7/gmm_cluster_covariances.csv
    conda-env: /scratch/work/luongn1/digirhythm-v2/.snakemake/conda/ab5233add898528c77eec06aa91604d6_

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2025-08-27T161628.619193.snakemake.log
WorkflowError:
At least one job did not complete successfully.
